require "date"
require "time"

desc "检测"
task :check do
  cd "_assets" do
    system "rm -rf javascripts/handie"
    system "cp -fR ../../dist/javascripts javascripts && mv javascripts/javascripts javascripts/handie"
    system "rm -rf stylesheets/handie"
    system "cp -fR ../../dist/stylesheets stylesheets && mv stylesheets/stylesheets stylesheets/handie"
  end

  cd "_demos" do
    system "rm -rf vendor"
    system "cp -fR ../../vendor ."
  end
end

desc "运行"
task :run do
  system "rake check"
  system "bundle exec jekyll serve --future --drafts --incremental"
end

desc "部署"
task :deploy do
  dir = "../../../sites/handie"

  if FileTest.directory?(dir)
    cd dir do
      # system "git reset --hard HEAD"
      system "git pull origin gh-pages"
    end
  end

  system "JEKYLL_ENV=production bundle exec jekyll build -V -d #{dir} --config _config.yml,_production.yml"

  cd dir do
    current_time = Time.now.strftime("%Y-%m-%d %H:%M:%S")

    system "touch .nojekyll"
    system "git add -A"
    system "git commit -m 'Generate on #{current_time}'"
    system "git push origin gh-pages"
  end
end
