require "date"
require "time"

desc "检测"
task :check do
  cd "_assets" do
    system "rm -rf javascripts/handie"
    system "cp -fR ../../dist/handie/javascripts javascripts && mv javascripts/javascripts javascripts/handie"
    system "rm -rf stylesheets/handie"
    system "cp -fR ../../dist/handie/stylesheets stylesheets && mv stylesheets/stylesheets stylesheets/handie"
    system "rm -rf images/handie"
    system "cp -fR ../../dist/handie/images images && mv images/images images/handie"
  end

  cd "_admin" do
    system "rm -rf vendor"
    system "cp -fR ../../dist ."
    system "rm -rf dist/handie"
    system "mv dist vendor"
  end
end

desc "运行"
task :run do
  system "bundle exec jekyll clean"
  system "rake check"
  system "bundle exec jekyll serve"
end

desc "部署"
task :deploy do
  dir = "../../../sites/handie"

  unless FileTest.directory?(dir)
    system "mkdir #{dir}"

    cd dir do
      system "git init"
      system "git remote add origin https://github.com/ourai/handie.git"
      system "git fetch"
      system "git checkout gh-pages"
    end
  else
    cd dir do
      # system "git reset --hard HEAD"
      system "git pull origin gh-pages"
    end
  end

  # 编译网站
  system "bundle exec jekyll clean"
  system "JEKYLL_ENV=production bundle exec jekyll build -V -d #{dir} --config _config.yml,_production.yml"
  system "cp ../build/README-dist.md #{dir}"

  cd dir do
    current_time = Time.now.strftime("%Y-%m-%d %H:%M:%S")

    system "mv README-dist.md README.md"
    system "touch .nojekyll"
    system "git add -A"
    system "git commit -m 'Generate on #{current_time}'"
    system "git push origin gh-pages"
  end
end
